[package]
name = "rusty_crypto"
version = "0.1.0"
edition = "2021"
authors = ["lopo<lopo@zju.edu.cn>"]
license = "MIT OR Apache-2.0"
keywords = ["crypto", "rusty", "wasm", "webassembly"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.83"
